name: ClientHub CI/CD

on:
  push:
    branches:
      - main

jobs:

  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run unit tests
        run: pytest tests/test_app.py

  e2e-tests:
    name: E2E tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Create CI environment file
        run: |
          echo "MYSQL_ROOT_PASSWORD=rootpassword" > .env
          echo "MYSQL_DATABASE=clienthub" >> .env
          echo "MYSQL_USER=clienthub_user" >> .env
          echo "MYSQL_PASSWORD=clienthubpassword" >> .env

      - name: Start application
        run: docker compose up -d

      - name: Wait for API and database
        run: |
          for i in {1..30}; do
            if curl -f http://localhost:8012/clients; then
              echo "API and database are ready"
              exit 0
            fi

            echo "Waiting for API and database..."
            sleep 2
          done

          echo "API or database did not become ready"
          docker compose logs
          exit 1

      - name: Run E2E tests
        run: pytest tests/test_e2e.py
      
      - name: Show Docker logs
        if: always()
        run: docker compose logs

      - name: Stop application
        if: always()
        run: docker compose down

  # ajout pour docker Hub
  build-and-push:
    name: Build and Push Docker image
    runs-on: ubuntu-latest
    needs:
      - unit-tests
      - e2e-tests

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./api  #enmplacement du dockerfile. Docker construit l'img a partir du dosseir api
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/clienthub:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/clienthub:${{ github.sha }}